#102 홈화면 배너 API 구현
Polaris-Sopterm/Polaris-BACKEND pull request #103
Opened 2021-07-11 15:04 UTC by bokdoll

+ 여정 목록 조회 API에서 응답 date 형식 수정

2021-07-12 05:09 UTC, ujusy requested changes

2021-07-12 06:03 UTC, bokdoll commented on routes/home/v0.js
> +  if (lastRetrospect || isSkipped || (!lastRetrospect && !lastJourney)) {
false/true의 boolean형식으로 받을 예정입니다! 수정하겠습니다~!

2021-07-12 06:03 UTC, bokdoll commented on routes/home/v0.js
> +  if (!isSkipped) throw new HttpBadRequest(Errors.HOME.IS_SKIPPED_MISSING);
그렇네요!!

2021-07-12 06:03 UTC, bokdoll commented on utils/homeBannerText.json
> +}
넵

2021-07-13 12:16 UTC, ujusy approved these changes

2021-07-13 12:16 UTC, merged

2021-07-13 12:17 UTC, ujusy commented
@bokdoll 👍👍👍👍👍👍 긴 API 여정이 끝나씁니다 😭
현주 postman으로 테스트는 되었어?

2021-07-13 13:28 UTC, bokdoll commented
포스트맨으로 이것저것 테스트해보긴 했는데,, 확신은 없어 🤔🥲