#10 모델 생성
Polaris-Sopterm/Polaris-BACKEND pull request #11
Opened 2021-04-27 14:18 UTC by bokdoll

- 모델 생성 (회고 테이블 제외)
- DB 마이그레이션
- constratints 작성

2021-04-27 15:02 UTC, ujusy requested changes

2021-04-28 15:24 UTC, ujusy requested changes

2021-04-28 15:24 UTC, ujusy commented on models/journey.js
> +      },
```suggestion
    createdAt: {
      allowNull: false,
      type: DataTypes.DATE(3),
      validate: {
        isDate: true,
        notNull: true,
      },
    },
    updatedAt: {
      allowNull: false,
      type: DataTypes.DATE(3),
      validate: {
        isDate: true,
        notNull: true,
      },
    },
      },
```

2021-04-28 15:24 UTC, ujusy commented on models/journey.js
> +    Journey.hasMany(models.ToDo);
```suggestion
    Journey.hasMany(models.ToDo, {
      foreignKey: 'userIdx',
      onDelete: 'CASCADE',
      onUpdate: 'CASCADE',
      sourceKey: 'idx',
    });
```

2021-04-28 15:24 UTC, ujusy commented on models/todo.js
> +    },
```suggestion
createdAt: {
      allowNull: false,
      type: DataTypes.DATE(3),
      validate: {
        isDate: true,
        notNull: true,
      },
    },
    updatedAt: {
      allowNull: false,
      type: DataTypes.DATE(3),
      validate: {
        isDate: true,
        notNull: true,
      },
    },
    },
```

2021-04-28 15:24 UTC, ujusy commented on models/todo.js
> +        allowNull: true,
```suggestion
      foreignKey: {
        name: 'journeyIdx',
        allowNull: true,
```

2021-04-28 15:24 UTC, ujusy commented on models/user.js
> +    User.hasMany(models.ToDo);
위에 hasMany 처럼 sourceKey, foreignKey 작성해주세요

2021-04-29 04:45 UTC, bokdoll commented on models/journey.js
> +      },
timestamps: true 옵션 줬는데도 이렇게 컬럼을 명시해줘야하는건가요??

2021-04-29 04:55 UTC, bokdoll commented on models/journey.js
> +    Journey.hasMany(models.ToDo);
남겨주신 내용 중에 78줄에서 foreignKey가 'userIdx'가 아니라 'journeyIdx'인거죵?

2021-04-29 05:36 UTC, ujusy commented on models/journey.js
> +      },
Date(3)  으로 안에 옵션주면 명시를 따로 해주어야합니다!

2021-04-29 05:45 UTC, bokdoll commented on models/journey.js
> +      },
아하! 그럼 models > users에서는 deleteAt도 포함해서 컬럼 추가하겠습니다!

2021-04-30 10:54 UTC, ujusy commented on models/journey.js
> +    Journey.hasMany(models.ToDo);
넵

2021-05-03 05:49 UTC, ujusy requested changes

2021-05-03 05:49 UTC, ujusy commented on migrations/20210427133002-create-initial-constraints.js
> +  },
try catch가 없습니다.. transaction 후에 commit하는 부분이 없어 반영되지 않습니다.
위의 파일과 동일한 형태로 구현해주세요

2021-05-03 05:57 UTC, bokdoll commented on migrations/20210427133002-create-initial-constraints.js
> +  },
헉 그렇네요! 수정해서 올리겠습니다.

2021-05-03 14:38 UTC, ujusy approved these changes

2021-05-03 14:38 UTC, merged