#30 여정 생성 API 구현
Polaris-Sopterm/Polaris-BACKEND pull request #33
Opened 2021-05-21 01:28 UTC by bokdoll

2021-05-21 14:49 UTC, ujusy requested changes

2021-05-21 14:49 UTC, ujusy commented on routes/journey/v0.js
> +  });
column이 value1, value2 이렇게 따로 되어있으니 body 값으로 value1, value2 이렇게 따로 받는게 어떨까요? 
따로 받게되면 코드가 훨씬 직관적으로 될 것 같습니다.

2021-05-21 14:49 UTC, ujusy commented on routes/journey/v0.js
> +  const value2 = !values[1] ? null : values[1];
```suggestion
```

2021-05-21 14:49 UTC, ujusy commented on routes/journey/v0.js
> +  };
```suggestion
  const journeyData = {
    title,
    value1,
    value2,
    weekInfo,
    date,
    userIdx: user.idx,
  };
```

2021-05-22 04:02 UTC, bokdoll commented on routes/journey/v0.js
> +  });
넵! 그렇겠네요~ 수정하겠습니다.

2021-05-22 18:39 UTC, ujusy approved these changes

2021-05-22 18:39 UTC, merged