#여정생성
Polaris-Sopterm/Polaris-BACKEND pull request #51
Opened 2021-05-24 14:16 UTC by bokdoll

2021-05-24 14:47 UTC, ujusy requested changes

2021-05-24 14:47 UTC, ujusy commented on migrations/20210524121900-alter-journeys-column.js
> +      });
```suggestion
    try {
      await queryInterface.renameColumn('journeys', 'weekInfo', 'weekNo', {transaction});
      await queryInterface.addColumn('journeys', 'year', {
        allowNull: false,
        type: Sequelize.UNSIGNED.INTEGER,
      }, {transaction});
      await queryInterface.addColumn('journeys', 'month', {
        allowNull: false,
        type: Sequelize.UNSIGNED.INTEGER,
      }, {transaction});
```

2021-05-24 14:47 UTC, ujusy commented on migrations/20210524121900-alter-journeys-column.js
> +      await queryInterface.removeColumn('journeys', 'month');
transaction 걸어주세요

2021-05-24 14:47 UTC, ujusy commented on models/journey.js
> +      },
unsigned int로 해야할 것 같아요

2021-05-24 14:53 UTC, bokdoll commented on migrations/20210524121900-alter-journeys-column.js
> +      await queryInterface.removeColumn('journeys', 'month');
넵!

2021-05-24 14:57 UTC, bokdoll commented on models/journey.js
> +      },
네!

2021-05-25 05:10 UTC, ujusy requested changes

2021-05-25 05:21 UTC, bokdoll commented on models/journey.js
> +        type: DataTypes.INTEGER.UNSIGNED,
아아 제가 마이그레이션 잘 몰라서 여쭤봅니다..!

제가 간단히 찾아봤는데 타입 변경할 때는 changeColumn을 하더라고요!
renameColumn 밑에 changeColumn으로 타입 변경하면 될까요~?

2021-05-25 05:23 UTC, ujusy commented on models/journey.js
> +        type: DataTypes.INTEGER.UNSIGNED,
넵넵 맞습니다 ㅎㅎ

2021-05-25 05:47 UTC, ujusy approved these changes

2021-05-25 05:47 UTC, merged