Feature/toDo
Polaris-Sopterm/Polaris-BACKEND pull request #84
Opened 2021-06-14 12:26 UTC by ujusy

2021-06-14 14:01 UTC, bokdoll requested changes

2021-06-14 14:01 UTC, bokdoll commented on routes/toDo/v0.js
>  module.exports = { router, createToDo, updateToDo };
여기 listToDoByJourneys 추가하면 좋을 것 같아요~

2021-06-16 00:55 UTC, bokdoll commented on routes/toDo/v0.js
> +      attributes: ['idx', 'title', 'value1', 'value2', 'year', 'month', 'weekNo'],
where에 userIdx가 들어가는 것 같은데 attributes에는 없는 것 같아요!

2021-06-16 00:55 UTC, bokdoll commented on routes/toDo/v0.js
> +        attributes: ['idx', 'title', 'isTop', 'isDone', 'date'],
date가 여정별 할일 뷰에서 ~월~일로 표시되는데, 해당 형식으로 보내주는 게 좋지 않을까요..? 제 개인적인 생각입니다..ㅎㅎ

2021-06-17 14:48 UTC, ujusy commented
@bokdoll  그 include안에 order하는거 정상적으로 안되는것 같아서 복돌양이 했던 방식 대로 order을 밖에 했는데 수정했을 때 정상적으로 됐나요?

2021-06-22 02:32 UTC, bokdoll commented on routes/toDo/v0.js
> +      toDo.dataValues.date = moment(utcDate).locale('ko').format('YYYY년 M월 D일 dddd');
여정별 할 일 보기는 0월 0일 0요일로 표시되는거 아닌가요~?

2021-06-22 02:34 UTC, bokdoll commented on routes/toDo/v0.js
> +      toDo.dataValues.date = moment(utcDate).locale('ko').format('YYYY년 M월 D일 dddd');
listToDoByDate에서도 0월 0일 0요일 아닌가요 ? .. ㅎㅎ

2021-06-22 02:37 UTC, ujusy commented on routes/toDo/v0.js
> +      toDo.dataValues.date = moment(utcDate).locale('ko').format('YYYY년 M월 D일 dddd');
dddd하면 요일로 나옵니다..! 년도는 제거할게용

2021-06-22 02:54 UTC, ujusy commented on routes/toDo/v0.js
> +      toDo.dataValues.date = moment(utcDate).locale('ko').format('YYYY년 M월 D일 dddd');
고쳐써용 ❤️❤️❤️

2021-06-22 02:58 UTC, bokdoll approved these changes

2021-06-22 02:58 UTC, merged