#41 여정 목록 API 구현
Polaris-Sopterm/Polaris-BACKEND pull request #85
Opened 2021-06-15 06:36 UTC by bokdoll

2021-06-15 12:02 UTC, ujusy requested changes

2021-06-15 12:03 UTC, ujusy commented
지금 test에러 나서 cloudbuild.yml에서 test부분삭제하고 올려주세요 ㅜㅜ

2021-06-16 00:44 UTC, bokdoll commented on routes/journey/v0.js
> +    });
네!

2021-06-16 01:18 UTC, ujusy approved these changes

2021-06-16 01:18 UTC, merged